ad_site/ad_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("classified_ads/", include("classified_ads.urls"))
]

ad_site/classified_ads/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'ads', views.AdViewSet)

app_name = "classified_ads"

urlpatterns = [
    path('', views.index, name="index"),
    path("<int:pk>/", views.detail, name="detail"),
    path("post/", views.post_ad, name="post"),
    path("login_register/", views.login_register, name="login_register"),
    path("register/", views.register, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("api/", include(router.urls)),
]

ad_site/classified_ads/models.py
from django.db import models
from django.contrib.auth import models as auth_models
from django.conf import settings


class Postable(models.Model):
    text = models.CharField(max_length=1000)
    date_posted = models.DateTimeField()
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL, null=True)

    class Meta:
        abstract = True

    def __str__(self) -> str:
        return self.text


class Ad(Postable):
    BUY = "Buy"
    SELL = "Sell"
    ad_type_choices = [
        (BUY, "Buy"),
        (SELL, "Sell")
    ]
    ad_type = models.CharField(
        max_length=4, choices=ad_type_choices)
    image = models.ImageField(
        null=True, blank=True, default=None)


class Comment(Postable):
    parent_ad = models.ForeignKey(Ad, on_delete=models.CASCADE)

    class Meta:
        ordering = ['date_posted']

ad_site/classified_ads/forms.py
from django import forms
from django.forms import ModelForm
from .models import Ad, Comment
from django.contrib.auth.models import User


class AdForm(ModelForm):
    class Meta:
        model = Ad
        fields = ["ad_type", "text",  "image"]
        labels = {
            "text": "Ad Description",
            "image": "Image (optional)",
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]
        labels = {
            "text": "Comment",
        }


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        help_texts = {
            "username": "",
        }

ad_site/classified_ads/views.py
from django.shortcuts import render, get_object_or_404
from .models import Ad, Comment
from django.utils import timezone
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib import auth
from .forms import AdForm, CommentForm, UserForm
from rest_framework import viewsets
from rest_framework import permissions
from .serializers import AdSerializer


# class IndexView(generic.ListView):
#     template_name = 'classified_ads/index.html'
#     context_object_name = 'latest_ads_list'

#     def get_queryset(self):
#         """Return the last 10 published ads."""
#         return Ad.objects.order_by("-date_posted")[:10]

def post_ad(request, ad_form):
    try:
        image = ad_form.cleaned_data["image"]
    except:
        image = None
    new_ad = Ad(text=ad_form.cleaned_data["text"],
                ad_type=request.POST["ad_type"],
                date_posted=timezone.now(),
                user=auth.get_user(request),
                image=image)
    new_ad.save()


def index(request):
    if request.method == 'POST':
        ad_form = AdForm(request.POST, request.FILES)
        if ad_form.is_valid():
            post_ad(request, ad_form)
            return HttpResponseRedirect(reverse('classified_ads:index'))
    else:
        ad_form = AdForm()
    latest_ads_list = Ad.objects.order_by("-date_posted")[:10]
    context_dict = {"latest_ads_list": latest_ads_list,
                    "ad_form": ad_form}
    return render(request, "classified_ads/index.html", context_dict)


# class DetailView(generic.DetailView):
#     model = Ad
#     template_name = 'classified_ads/detail.html'

#     def get_context_data(self, **kwargs):
#         # Call the base implementation first to get a context
#         context = super().get_context_data(**kwargs)
#         # Add in a QuerySet of all the books
#         context['comment_list'] = Ad.objects.all()
#         return context


def post_comment(request, comment_form, ad):
    new_comment = Comment(parent_ad=ad,
                          text=comment_form.cleaned_data["text"],
                          date_posted=timezone.now(),
                          user=auth.get_user(request))
    new_comment.save()
    ad.comment_set.add(new_comment)


def detail(request, pk):
    ad = get_object_or_404(Ad, pk=pk)
    if request.method == 'POST':

        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            post_comment(request, comment_form, ad)
            return HttpResponseRedirect(
                reverse('classified_ads:detail', kwargs={"pk": pk}))
    else:
        comment_form = CommentForm()
    context_dict = {"ad": ad, "comment_form": comment_form}
    return render(request, "classified_ads/detail.html", context_dict)


def login_register(request):
    user_form = UserForm()
    context_dict = {"user_form": user_form}
    return render(request, "classified_ads/login_register.html", context_dict)


def register(request):

    User.objects.create_user(username=request.POST["username"],
                             password=request.POST["password"])
    return HttpResponseRedirect(reverse('classified_ads:index'))


def login_view(request):
    attempted_user = auth.authenticate(username=request.POST["username"],
                                       password=request.POST["password"])
    login_is_successful = attempted_user is not None
    if login_is_successful:
        auth.login(request, attempted_user)
        return HttpResponseRedirect(reverse('classified_ads:index'))
    else:
        return HttpResponse("Login failed")


def logout_view(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('classified_ads:index'))


class AdViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows ads to be viewed.
    """
    queryset = Ad.objects.all()
    serializer_class = AdSerializer
    permission_classes = [permissions.AllowAny]

ad_site/classified_ads/templates/classified_ads/base.html
<!DOCTYPE html>
<html>
{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static 'classified_ads/style.css' %}">
{% endblock css %}



<body>

  {% block header %}

  <nav>
    <div class="heading">
      <h1>Eric's Classified Ad Site</h1>
    </div>

    <ul class="nav-links">

      <li><a href="{% url 'classified_ads:index'%}">Home</a></li>

    </ul>

    {% block login_status %}
    <div class="login-status">
      {% if user.is_authenticated %}

      Welcome, {{ user.username }}. Thanks for logging in.
      <a href="{% url 'classified_ads:logout'%}">Logout</a>

      {% else %}

      Welcome, new user. Please log in or register.
      <a href="{% url 'classified_ads:login_register'%}">Login/Register</a>
      {% endif %}
    </div>
    {% endblock login_status %}

  </nav>
  {% endblock header %}

  <h2>
    {% block page_title %}
    {% endblock page_title %}
  </h2>

  {% block content %}
  Your content here!!!
  {% endblock content %}

</body>

</html>
{% block js %}
{% endblock js %}

ad_site/classified_ads/templates/classified_ads/detail.html
{% extends "classified_ads/base.html" %}

{% block page_title %}
{{ ad.text }}
{% endblock page_title %}

{% block content %}



- Posted by {{ad.user.username}} on {{ad.date_posted}}
<br>

{% if ad.image %}
{% load static %}
<img src="{% static 'classified_ads'%}{{ad.image.url}}">
{% endif %}

<hr>
<h2>Comments</h2>
<ul>
  {% for comment in ad.comment_set.all %}
  <li>{{ comment.text }}
    Posted on: {{ comment.date_posted }} by {{ comment.user.username }}</li>
  {% endfor %}
</ul>

{% if user.is_authenticated %}

<form action=" {% url 'classified_ads:detail' ad.id %}" method="post">
  {% csrf_token %}
  <b>Post a comment</b>
  {{comment_form.as_div}}
  <input type="submit" value="Post">
</form>

{% else %}
You cannot post comments without logging in.
{% endif %}

{% endblock content %}

ad_site/classified_ads/templates/classified_ads/index.html
{% extends "classified_ads/base.html" %}

{% block page_title %}
Recent Ad Listings
{% endblock page_title %}

{% block js %}
{% load static %}
<!-- <script src="{% static 'classified_ads/test_script.js' %}"></script> -->
<script src="{% static 'classified_ads/react.js' %}"></script>
<script src="{% static 'classified_ads/react_dom.js' %}"></script>
<script src="{% static 'classified_ads/babel.js' %}"></script>
<script type="text/babel" src="{% static 'classified_ads/index.js' %}"></script>
{% endblock js %}

{% block content %}
<div class="app-mountpoint">
  <!-- If the script for the React filterable ad list fails, then
the static ad list will take its place, since the static ad list is surrounded 
by the app-mountpoint tags -->
  {% if latest_ads_list %}
  <ul>
    {% for ad in latest_ads_list %}
    <li><a href="{% url 'classified_ads:detail' ad.id %}">{{ ad.text }}</a>
      Posted on: {{ ad.date_posted }} by {{ ad.user.username }}</li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No ads have been posted.</p>
  {% endif %}
</div>

{% if user.is_authenticated %}
<b>Post an ad</b>
<form action="{% url 'classified_ads:index'%}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ ad_form.as_div }}
  <input type="submit" value="Post">
</form>

{% else %}
You cannot post ads without logging in.
{% endif %}

{% endblock content %}

ad_site/classified_ads/templates/classified_ads/login_register.html
{% extends "classified_ads/base.html" %}

{% block content %}

<h3> Register </h3>

<form action="{% url 'classified_ads:register'%}" method="post">
  {% csrf_token %}
  {{user_form.as_div}}
  <input type="submit" value="Register">
</form>

<br>

<h3> Login </h3>

<form action="{% url 'classified_ads:login'%}" method="post">
  {% csrf_token %}
  {{user_form.as_div}}
  <input type="submit" value="Login">
</form>

{% endblock content %}